-- 기존 게임 데이터 초기화 후 실제 게임 목록 삽입
-- Supabase SQL Editor에서 실행하세요

-- 1. 기존 데이터 삭제 (연관 데이터 포함)
delete from reviews;
delete from play_records;
delete from venue_games;
delete from venues;
delete from games;

-- 2. games 테이블 컬럼 추가 (없으면 추가)
alter table games
  add column if not exists rec_min_players int,
  add column if not exists rec_max_players int,
  add column if not exists max_duration_minutes int,
  add column if not exists requires_gm boolean not null default false;

-- 3. 게임 데이터 삽입 (253개)
insert into games (id, title, description, themes, difficulty, min_players, max_players, rec_min_players, rec_max_players, duration_minutes, max_duration_minutes, requires_gm, avg_rating, review_count)
values
  (uuid_generate_v4(), '서스펙트 게임 : 클로즈드 서클 미스터리', '', '{}', 'intermediate', 4, 4, 4, 4, 120, 480, false, 0, 0),
  (uuid_generate_v4(), '서스펙트 게임 : 리로드', '', '{}', 'intermediate', 3, 3, 3, 3, 120, 480, false, 0, 0),
  (uuid_generate_v4(), '껍질 속 세상', '', '{}', 'intermediate', 7, 8, 7, 8, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '새장 속 제비는 꿈을 꾼다', '', '{}', 'intermediate', 9, 9, 9, 9, 180, NULL, false, 0, 0),
  (uuid_generate_v4(), '(번역본) 미스터리 파티 시리즈 : 알바트로스의 황금비', '', '{}', 'intermediate', 5, 6, 5, 6, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '(번역본) 미스터리 파티 시리즈 : 누구를 위하여 전서구는 나는가', '', '{}', 'intermediate', 6, 7, 6, 7, 180, NULL, false, 0, 0),
  (uuid_generate_v4(), '(번역본) 미스터리 파티 시리즈 : <3월 토끼>의 귀신 찾기', '', '{}', 'intermediate', 6, 7, 6, 7, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '(번역본) 미스터리 파티 시리즈 : 령가', '', '{}', 'intermediate', 5, 6, 5, 6, 180, NULL, false, 0, 0),
  (uuid_generate_v4(), '미스터리 파티 시리즈 : 죄와 벌의 도서관', '', '{}', 'intermediate', 5, 6, 5, 6, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '미스터리 파티 시리즈 : 늑대인간 마을의 축제', '', '{}', 'intermediate', 7, 8, 7, 8, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '미스터리 파티 시리즈 : 구두룡 저택의 살인', '', '{}', 'intermediate', 7, 9, 7, 9, 120, 180, false, 0, 0),
  (uuid_generate_v4(), '미스터리 파티 시리즈 : 끝나지 않는 한여름', '', '{}', 'intermediate', 8, 9, 8, 9, 180, NULL, false, 0, 0),
  (uuid_generate_v4(), '미스터리 파티 시리즈 : 몇번이고 푸른 달에 불을 붙였다', '', '{}', 'intermediate', 6, 7, 6, 7, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '미스터리 파티 시리즈 : 용사가 죽었다', '', '{}', 'intermediate', 6, 8, 6, 8, 180, NULL, false, 0, 0),
  (uuid_generate_v4(), '미스터리 파티 시리즈 : 다크 율에 속죄를', '', '{}', 'intermediate', 7, 9, 7, 9, 180, NULL, false, 0, 0),
  (uuid_generate_v4(), '미스터리 파티 시리즈 : 게놈의 탑', '', '{}', 'intermediate', 7, 7, 7, 7, 180, NULL, false, 0, 0),
  (uuid_generate_v4(), '미스터리 파티 시리즈 : 마녀는 황혼의 종에 사라진다', '', '{}', 'intermediate', 6, 7, 6, 7, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '미스터리 파티 시리즈 : 기상천외, 암네시아', '', '{}', 'intermediate', 7, 7, 7, 7, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '미스터리 파티 시리즈 : 흰 까마귀, 붉게 물들다', '', '{}', 'intermediate', 6, 7, 6, 7, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '미스터리 파티 시리즈 : 강변 밤의 꿈', '', '{}', 'intermediate', 6, 7, 6, 7, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '4명의 탐정과 물의 유령', '', '{}', 'intermediate', 9, 9, 9, 9, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '머더 미스터리 미니 : 교토 이세계 투어', '', '{}', 'intermediate', 4, 4, 4, 4, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '머더 미스터리 미니 : 최후의 수아레', '', '{}', 'intermediate', 5, 5, 5, 5, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '머더 미스터리 미니 : 별장살인', '', '{}', 'intermediate', 5, 6, 5, 6, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '머더 미스터리 미니 : 주말의 살인귀', '', '{}', 'intermediate', 2, 2, 2, 2, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '머더 미스터리 미니 : 시간을 달리는 트라이앵글', '', '{}', 'intermediate', 3, 3, 3, 3, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '머더 미스터리 미니 : 웬디, 어른이 되렴', '', '{}', 'intermediate', 4, 5, 4, 5, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '머더 미스터리 미니 : 시체와 온천', '', '{}', 'intermediate', 4, 5, 4, 5, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '머더 미스터리 미니 : 미싱 파이터', '', '{}', 'intermediate', 4, 4, 4, 4, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '머더 미스터리 미니 : 보랏못 리라이트', '', '{}', 'intermediate', 2, 2, 2, 2, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '머더 미스터리 미니 : 카나리아는 지저귀지 않는다', '', '{}', 'intermediate', 4, 4, 4, 4, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '머더 미스터리 미니 : 안개가 떨어지는 고개', '', '{}', 'intermediate', 4, 4, 4, 4, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '머더 미스터리 미니 : 문스톤 저택 살인 사건', '', '{}', 'intermediate', 4, 4, 4, 4, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '스위트홈 : 작은 교회', '', '{}', 'intermediate', 4, 4, 4, 4, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '로맨스 판타지 속에서 살아남는 방법에 대하여', '', '{}', 'intermediate', 5, 5, 5, 5, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '비틀거리는 카나리아에게', '', '{}', 'intermediate', 2, 2, 2, 2, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '마법사와 잠자는 숲', '', '{}', 'intermediate', 2, 2, 2, 2, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '인사이드 팩트 : 낙원의 밤', '', '{}', 'intermediate', 2, 2, 2, 2, 100, NULL, false, 0, 0),
  (uuid_generate_v4(), '인사이드 팩트 : 삼지도', '', '{}', 'intermediate', 2, 2, 2, 2, 100, NULL, false, 0, 0),
  (uuid_generate_v4(), '인사이드 팩트 : 날씨는 맑음', '', '{}', 'intermediate', 2, 2, 2, 2, 100, NULL, false, 0, 0),
  (uuid_generate_v4(), '인사이드 팩트 : 미씽...', '', '{}', 'intermediate', 2, 2, 2, 2, 100, NULL, false, 0, 0),
  (uuid_generate_v4(), '인사이드 팩트 : 반짝반짝 빛나는', '', '{}', 'intermediate', 2, 2, 2, 2, 100, NULL, false, 0, 0),
  (uuid_generate_v4(), '인사이드 팩트 : 카르마', '', '{}', 'intermediate', 2, 2, 2, 2, 100, NULL, false, 0, 0),
  (uuid_generate_v4(), '인사이드 팩트 : 제아의 눈', '', '{}', 'intermediate', 2, 2, 2, 2, 100, NULL, false, 0, 0),
  (uuid_generate_v4(), '인사이드 팩트 : 무너져가는 고성에...', '', '{}', 'intermediate', 2, 2, 2, 2, 100, NULL, false, 0, 0),
  (uuid_generate_v4(), '인사이드 팩트 : 마지막 베팅', '', '{}', 'intermediate', 2, 2, 2, 2, 100, NULL, false, 0, 0),
  (uuid_generate_v4(), '탐정 시드 업다이크 : 칼라미티 트루퍼즈', '', '{}', 'intermediate', 6, 6, 6, 6, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '탐정 시드 업다이크 : 리썰 캐쉬', '', '{}', 'intermediate', 6, 6, 6, 6, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '탐정 시드 업다이크 : 슬로터즈 팰리스', '', '{}', 'intermediate', 6, 6, 6, 6, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '탐정 시드 업다이크 : 모노스태틱 엑스', '', '{}', 'intermediate', 6, 6, 6, 6, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '탐정 시드 업다이크 : 에이전트 버서스', '', '{}', 'intermediate', 5, 5, 5, 5, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '스페이스퐁퐁호 살인사건', '', '{}', 'intermediate', 4, 4, 4, 4, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '퇴사하려 했을 뿐인데 김부장이 죽은 건에 대하여', '', '{}', 'intermediate', 4, 5, 4, 5, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '퇴사하자마자 하필 이세계 소환된 건에 관하여', '', '{}', 'intermediate', 4, 5, 4, 5, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), 'CODEX GIGAS part.1', '', '{}', 'intermediate', 5, 5, 5, 5, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), 'CODEX GIGAS part.2', '', '{}', 'intermediate', 5, 5, 5, 5, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '작가와의 만남', '', '{}', 'intermediate', 5, 6, 5, 6, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '불꽃놀이', '', '{}', 'intermediate', 5, 6, 5, 6, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '마법학교의 혼혈아들이 금지된 마도서를 해독하려다 모두 죽은 사건', '', '{}', 'intermediate', 6, 6, 6, 6, 180, NULL, false, 0, 0),
  (uuid_generate_v4(), '얼어붙은 당신에게 6개의 등불을', '', '{}', 'intermediate', 6, 6, 6, 6, 210, NULL, false, 0, 0),
  (uuid_generate_v4(), '북부대공을 암살하는 법', '', '{}', 'intermediate', 5, 5, 5, 5, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '시인촌기담', '', '{}', 'intermediate', 6, 6, 6, 6, 180, NULL, false, 0, 0),
  (uuid_generate_v4(), '기계섬기담', '', '{}', 'intermediate', 6, 6, 6, 6, 180, NULL, false, 0, 0),
  (uuid_generate_v4(), '우물에 깃든 소리', '', '{}', 'intermediate', 4, 4, 4, 4, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '그날이 오면', '', '{}', 'intermediate', 4, 4, 4, 4, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '미스터리 앤 어드벤처 01 : 분가', '', '{}', 'intermediate', 5, 6, 5, 6, 180, NULL, false, 0, 0),
  (uuid_generate_v4(), '미스터리 앤 어드벤처 02 : 8월의 타임머신', '', '{}', 'intermediate', 6, 7, 6, 7, 180, NULL, false, 0, 0),
  (uuid_generate_v4(), '미스터리 앤 어드벤처 03 : 귀면도시수사file', '', '{}', 'intermediate', 6, 6, 6, 6, 180, NULL, false, 0, 0),
  (uuid_generate_v4(), '미스터리 앤 어드벤처 04 : 탐정금지영역', '', '{}', 'intermediate', 6, 6, 6, 6, 240, NULL, false, 0, 0),
  (uuid_generate_v4(), '망자의 진술', '', '{}', 'intermediate', 5, 5, 5, 5, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '버틀런트 저택의 비밀', '', '{}', 'intermediate', 7, 7, 7, 7, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '감자의 꿈', '', '{}', 'intermediate', 5, 5, 5, 5, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '테르모필라이의 협잡꾼', '', '{}', 'intermediate', 7, 7, 7, 7, 150, 180, false, 0, 0),
  (uuid_generate_v4(), '보물섬', '', '{}', 'intermediate', 7, 7, 7, 7, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '최후의 마을', '', '{}', 'intermediate', 7, 7, 7, 7, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '무경고등학교', '', '{}', 'intermediate', 6, 6, 6, 6, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '폭풍과 함께 마왕이 오셨도다', '', '{}', 'intermediate', 4, 4, 4, 4, 70, NULL, false, 0, 0),
  (uuid_generate_v4(), '데스트루도', '', '{}', 'intermediate', 5, 5, 5, 5, 160, NULL, false, 0, 0),
  (uuid_generate_v4(), '설령 테세우스의 배의 작은 얼룩에 불과할지라도', '', '{}', 'intermediate', 5, 5, 5, 5, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '오늘 내가 죽었다', '', '{}', 'intermediate', 5, 5, 5, 5, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '0719 : 낙하를 향하는 두개의 수', '', '{}', 'intermediate', 4, 4, 4, 4, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '혈석류학원 : 소녀의 미소편', '', '{}', 'intermediate', 5, 5, 5, 5, 180, NULL, false, 0, 0),
  (uuid_generate_v4(), '라이노 교수가 아는 다가올 오늘 중의 죽음', '', '{}', 'intermediate', 5, 5, 5, 5, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '기명은 귀록에 두 번 오른다', '', '{}', 'intermediate', 4, 4, 4, 4, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '침식', '', '{}', 'intermediate', 6, 6, 6, 6, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '별의 추락', '', '{}', 'intermediate', 4, 4, 4, 4, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '영원한 졸업식', '', '{}', 'intermediate', 5, 5, 5, 5, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '달님. 제 소원을 들어주세요', '', '{}', 'intermediate', 5, 6, 5, 6, 210, NULL, false, 0, 0),
  (uuid_generate_v4(), '빨간 모자, 무도회에서 시체와 만나다', '', '{}', 'intermediate', 4, 4, 4, 4, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '트로이메라이', '', '{}', 'intermediate', 3, 3, 3, 3, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '슬럼독스 / 탐정은 춤춘다', '', '{}', 'intermediate', 4, 4, 4, 4, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '일백마을 살인사건', '', '{}', 'intermediate', 4, 5, 4, 5, 100, 120, false, 0, 0),
  (uuid_generate_v4(), '판도라의 택배', '', '{}', 'intermediate', 5, 5, 5, 5, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '아스토리아의 표징', '', '{}', 'intermediate', 5, 5, 5, 5, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '괴조는 깊은 탄식의 끝에', '', '{}', 'intermediate', 4, 4, 4, 4, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '레드x리그렛', '', '{}', 'intermediate', 5, 5, 5, 5, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '카르네아데스의 음영', '', '{}', 'intermediate', 4, 8, 4, 8, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '데스게임-데스테스트  ~기억 잃은 답안지~', '', '{}', 'intermediate', 4, 4, 4, 4, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '모텔 노바디(Motel Nobody)', '', '{}', 'intermediate', 4, 4, 4, 4, 150, 180, false, 0, 0),
  (uuid_generate_v4(), '낙원주점', '', '{}', 'intermediate', 4, 4, 4, 4, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '설화와 회색빛 몽견초', '', '{}', 'intermediate', 5, 5, 5, 5, 70, NULL, false, 0, 0),
  (uuid_generate_v4(), '설화와 해바라기 베이커리', '', '{}', 'intermediate', 5, 5, 5, 5, 70, NULL, false, 0, 0),
  (uuid_generate_v4(), '552111152 : BEHIND', '', '{}', 'intermediate', 5, 6, 5, 6, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '테러라이즈', '', '{}', 'intermediate', 4, 5, 4, 5, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '캐치크라임 - 복덕방 살인사건, 귀곡산장 살인사건', '', '{}', 'intermediate', 3, 4, 3, 4, 60, 120, false, 0, 0),
  (uuid_generate_v4(), '럭키언럭키', '', '{}', 'intermediate', 3, 5, 5, 5, 40, 60, false, 0, 0),
  (uuid_generate_v4(), '천안대학교 민속학연구 동아리 활동보고서 #벌명당산', '', '{}', 'intermediate', 5, 5, 5, 5, 120, 150, true, 0, 0),
  (uuid_generate_v4(), '원고용지는 알고있다', '', '{}', 'intermediate', 4, 4, 4, 4, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '황홀한 돼지', '', '{}', 'intermediate', 4, 4, 4, 4, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '크세르크세스의 그림자', '', '{}', 'intermediate', 4, 4, 4, 4, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '몽환의 세계와 비밀의 사랑', '', '{}', 'intermediate', 4, 5, 4, 5, 90, 150, false, 0, 0),
  (uuid_generate_v4(), '앵커 미스터리 : 서양식 갑옷이 우는 저택 / 코로나가 잦아든 땅에서', '', '{}', 'intermediate', 3, 4, 3, 4, 150, 180, false, 0, 0),
  (uuid_generate_v4(), '마지막여행', '', '{}', 'intermediate', 6, 6, 6, 6, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '무령', '', '{}', 'intermediate', 4, 5, 4, 5, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '이세계의 성녀는 해방을 꿈꾼다', '', '{}', 'intermediate', 3, 3, 3, 3, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '별빛 우주 페러렐라인', '', '{}', 'intermediate', 5, 5, 5, 5, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '오늘, 벚꽃이 죽어버렸다', '', '{}', 'intermediate', 5, 5, 5, 5, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), 'DOTs x LINEs 에피소드:결단', '', '{}', 'intermediate', 2, 2, 2, 2, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '파랑새', '', '{}', 'intermediate', 4, 4, 4, 4, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '기울어진 천칭의 운명', '', '{}', 'intermediate', 4, 4, 4, 4, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '랭던가의 망령', '', '{}', 'intermediate', 2, 2, 2, 2, 80, NULL, false, 0, 0),
  (uuid_generate_v4(), '숨겨진 이야기 H', '', '{}', 'intermediate', 4, 4, 4, 4, 120, 150, false, 0, 0),
  (uuid_generate_v4(), '개화, 꽃피우다', '', '{}', 'intermediate', 4, 4, 4, 4, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '화가의 마지막 메시지', '', '{}', 'intermediate', 4, 4, 4, 4, 100, NULL, false, 0, 0),
  (uuid_generate_v4(), '파란, 배신의 물결', '', '{}', 'intermediate', 4, 4, 4, 4, 100, NULL, false, 0, 0),
  (uuid_generate_v4(), '사라진 속옷과 하늘을 나는 물고기', '', '{}', 'intermediate', 5, 5, 5, 5, 60, 90, false, 0, 0),
  (uuid_generate_v4(), '로나에나 - 재앙의 선물', '', '{}', 'intermediate', 5, 5, 5, 5, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '운명의 세 여신 : ep1. 베르단디', '', '{}', 'intermediate', 4, 4, 4, 4, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '운명의 세 여신 : ep2. 스쿨드', '', '{}', 'intermediate', 4, 4, 4, 4, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '운명의 세 여신 : ep3. 우르드', '', '{}', 'intermediate', 4, 4, 4, 4, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '종이 울릴 때까지 신데렐라', '', '{}', 'intermediate', 6, 6, 6, 6, 180, NULL, false, 0, 0),
  (uuid_generate_v4(), '데드박스', '', '{}', 'intermediate', 2, 2, 2, 2, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '보통의 머더미스터리', '', '{}', 'intermediate', 5, 5, 5, 5, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '그림자찾기', '', '{}', 'intermediate', 6, 6, 6, 6, 200, 300, false, 0, 0),
  (uuid_generate_v4(), '에이다', '', '{}', 'intermediate', 5, 5, 5, 5, 120, 240, false, 0, 0),
  (uuid_generate_v4(), '양심의 기생', '', '{}', 'intermediate', 3, 3, 3, 3, 120, NULL, true, 0, 0),
  (uuid_generate_v4(), '살인라이브', '', '{}', 'intermediate', 5, 5, 5, 5, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '프로젝트 노아', '', '{}', 'intermediate', 4, 4, 4, 4, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '이 어둠을 당신과', '', '{}', 'intermediate', 6, 6, 6, 6, 200, NULL, false, 0, 0),
  (uuid_generate_v4(), '유각관의 살인', '', '{}', 'intermediate', 6, 6, 6, 6, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '지구에서 사랑을 담아', '', '{}', 'intermediate', 7, 7, 7, 7, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), 'DEJA VU', '', '{}', 'intermediate', 3, 3, 3, 3, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '저승으로부터의 편지', '', '{}', 'intermediate', 4, 4, 4, 4, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '사라진 선생님', '', '{}', 'intermediate', 5, 6, 5, 6, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '루시드', '', '{}', 'intermediate', 6, 7, 6, 7, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '레거시', '', '{}', 'intermediate', 5, 5, 5, 5, 110, NULL, false, 0, 0),
  (uuid_generate_v4(), '리그렛', '', '{}', 'intermediate', 5, 6, 5, 6, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '압록강', '', '{}', 'intermediate', 2, 2, 2, 2, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '격리', '', '{}', 'intermediate', 2, 2, 2, 2, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '천서', '', '{}', 'intermediate', 4, 4, 4, 4, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '포르투나호 살인사건', '', '{}', 'intermediate', 4, 4, 4, 4, 100, NULL, false, 0, 0),
  (uuid_generate_v4(), '시리게도, 봄이었다', '', '{}', 'intermediate', 5, 5, 5, 5, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), 'Moonstruck', '', '{}', 'intermediate', 4, 4, 4, 4, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '외계인이 내려와 하는 말', '', '{}', 'intermediate', 6, 6, 6, 6, 120, NULL, true, 0, 0),
  (uuid_generate_v4(), 'DHD', '', '{}', 'intermediate', 2, 2, 2, 2, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '두근두근 고백대소동', '', '{}', 'intermediate', 4, 4, 4, 4, 100, NULL, false, 0, 0),
  (uuid_generate_v4(), '경성30분 불온한 자는 명랑하라', '', '{}', 'intermediate', 5, 6, 5, 6, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), 'Last Birthday', '', '{}', 'intermediate', 6, 7, 6, 7, 180, NULL, false, 0, 0),
  (uuid_generate_v4(), '경성야화록', '', '{}', 'intermediate', 4, 4, 4, 4, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), 'Paimon', '', '{}', 'intermediate', 4, 4, 4, 4, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '늑대 무리 속 침묵', '', '{}', 'intermediate', 6, 6, 6, 6, 180, NULL, false, 0, 0),
  (uuid_generate_v4(), 'SORCIER 현자들의 이야기', '', '{}', 'intermediate', 5, 5, 5, 5, 150, NULL, true, 0, 0),
  (uuid_generate_v4(), 'SOMMEIL(소메이유)', '', '{}', 'intermediate', 5, 5, 5, 5, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '유령섬 살인사건 : First Loop', '', '{}', 'intermediate', 4, 4, 4, 4, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '유령섬 Next Loop : 비극의 반복으로', '', '{}', 'intermediate', 4, 4, 4, 4, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '유령섬 Final Loop : 비극의 종막으로', '', '{}', 'intermediate', 4, 4, 4, 4, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '유령섬 Before : 비극의 시작으로', '', '{}', 'intermediate', 1, 4, 1, 4, 30, NULL, false, 0, 0),
  (uuid_generate_v4(), '크림향 낭자한 만쥬의 죽음', '', '{}', 'intermediate', 4, 4, 4, 4, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '문어형님 타코야끼 조리사건', '', '{}', 'intermediate', 4, 4, 4, 4, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '마이 머더 미스터리 Vol.1 최종 프로토콜', '', '{}', 'intermediate', 5, 7, 5, 7, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '마이 머더 미스터리 Vol.2 원숭이의 죽음', '', '{}', 'intermediate', 5, 7, 5, 7, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '별주부전_토끼의 죽음', '', '{}', 'intermediate', 5, 5, 5, 5, 100, NULL, false, 0, 0),
  (uuid_generate_v4(), '6인의 죄인', '', '{}', 'intermediate', 6, 6, 6, 6, 180, NULL, false, 0, 0),
  (uuid_generate_v4(), '달콤한 노랑', '', '{}', 'intermediate', 5, 5, 5, 5, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '남쪽 하늘의 폴라리스', '', '{}', 'intermediate', 5, 5, 5, 5, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '이세계를 구할 완벽한 파티입니다만?', '', '{}', 'intermediate', 4, 4, 4, 4, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '꽃이 지던 날', '', '{}', 'intermediate', 4, 4, 4, 4, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '심해의 사계', '', '{}', 'intermediate', 7, 7, 7, 7, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '눈이 멈추기 전에', '', '{}', 'intermediate', 5, 5, 5, 5, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '동상이몽', '', '{}', 'intermediate', 6, 6, 6, 6, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '다시금 피어난 불꽃은', '', '{}', 'intermediate', 5, 5, 5, 5, 180, NULL, false, 0, 0),
  (uuid_generate_v4(), '초능력 학원 머더파일 "봉인된 연구실의 비극"', '', '{}', 'intermediate', 3, 4, 3, 4, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '초능력 학원 머더파일 "꿈을 조작하는 자"', '', '{}', 'intermediate', 3, 4, 3, 4, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '레드 씬 : 마지막 테이크', '', '{}', 'intermediate', 4, 4, 4, 4, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '검은 훈장 : 기록 없는 과거', '', '{}', 'intermediate', 4, 4, 4, 4, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '탐욕 part.01 : 탐욕의 저택', '', '{}', 'intermediate', 4, 4, 4, 4, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '블루노트보다 창백한', '', '{}', 'intermediate', 5, 5, 5, 5, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '누가 고양이를 죽였나', '', '{}', 'intermediate', 5, 5, 5, 5, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '백제금동대향로 : 종주의 밤', '', '{}', 'intermediate', 5, 5, 5, 5, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '호텔 레드럼 ep1. 푸른 죽음', '', '{}', 'intermediate', 5, 5, 5, 5, 100, NULL, false, 0, 0),
  (uuid_generate_v4(), '호텔 레드럼 ep2. 노란 죽음', '', '{}', 'intermediate', 5, 5, 5, 5, 100, NULL, false, 0, 0),
  (uuid_generate_v4(), 'Closed File File#1 욕실 사고사', '', '{}', 'intermediate', 5, 5, 5, 5, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), 'Closed File File#2 백화점 마네킹', '', '{}', 'intermediate', 5, 5, 5, 5, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '6중주의 가면무도회', '', '{}', 'intermediate', 5, 6, 5, 6, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), 'Y의 장례식', '', '{}', 'intermediate', 4, 4, 4, 4, 90, 180, false, 0, 0),
  (uuid_generate_v4(), '목 베는 마을', '', '{}', 'intermediate', 5, 5, 5, 5, 60, 180, false, 0, 0),
  (uuid_generate_v4(), '바 앤 호텔', '', '{}', 'intermediate', 4, 4, 4, 4, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '암흑과 흑막', '', '{}', 'intermediate', 4, 4, 4, 4, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '오마쥬 : 미술관 살인사건', '', '{}', 'intermediate', 4, 4, 4, 4, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), 'Disaster', '', '{}', 'intermediate', 3, 4, 3, 4, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '망령열차', '', '{}', 'intermediate', 4, 4, 4, 4, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '백귀야행', '', '{}', 'intermediate', 6, 6, 6, 6, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '뮤지컬펜션 살인사건', '', '{}', 'intermediate', 5, 5, 5, 5, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '절벽산장 살인사건', '', '{}', 'intermediate', 4, 5, 4, 5, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '만월사당 살인사건', '', '{}', 'intermediate', 5, 6, 5, 6, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), 'BUT.', '', '{}', 'intermediate', 5, 5, 5, 5, 90, 130, false, 0, 0),
  (uuid_generate_v4(), '비더리타', '', '{}', 'intermediate', 5, 5, 5, 5, 50, 100, false, 0, 0),
  (uuid_generate_v4(), '그렇게 X는 다시 태어났다', '', '{}', 'intermediate', 5, 5, 5, 5, 80, 120, false, 0, 0),
  (uuid_generate_v4(), 'HAPPY XOO MUCH', '', '{}', 'intermediate', 4, 4, 4, 4, 80, 100, false, 0, 0),
  (uuid_generate_v4(), '뻐꾸기 X끼는 울지 않는다.', '', '{}', 'intermediate', 5, 5, 5, 5, 50, 80, false, 0, 0),
  (uuid_generate_v4(), '안개 여각의 죽음', '', '{}', 'intermediate', 4, 4, 4, 4, 100, NULL, false, 0, 0),
  (uuid_generate_v4(), '웸블리 타운의 친절한 이웃들 : 웰시코기 살인사건', '', '{}', 'intermediate', 4, 4, 4, 4, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '권력', '', '{}', 'intermediate', 4, 4, 4, 4, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '여름방학의 흡혈귀', '', '{}', 'intermediate', 5, 5, 5, 5, 150, NULL, true, 0, 0),
  (uuid_generate_v4(), '사라진 귀걸이를 찾아라', '', '{}', 'intermediate', 4, 4, 4, 4, 150, NULL, false, 0, 0),
  (uuid_generate_v4(), '형사들의 유배지', '', '{}', 'intermediate', 1, 6, 6, 6, 180, NULL, false, 0, 0),
  (uuid_generate_v4(), '주마등은 흰색으로 빛난다', '', '{}', 'intermediate', 3, 3, 3, 3, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '기억 저장 장치', '', '{}', 'intermediate', 4, 5, 4, 5, 100, 120, false, 0, 0),
  (uuid_generate_v4(), '실험실, 소란', '', '{}', 'intermediate', 4, 5, 4, 5, 100, 120, false, 0, 0),
  (uuid_generate_v4(), '아스모데우스의 만찬', '', '{}', 'intermediate', 4, 4, 4, 4, 90, NULL, false, 0, 0),
  (uuid_generate_v4(), '메모리즈 3부작 Ep1. 용사님을 찾습니다', '', '{}', 'intermediate', 5, 5, 5, 5, 80, NULL, false, 0, 0),
  (uuid_generate_v4(), '메모리즈 3부작 Ep2. 동화작가의 죽음', '', '{}', 'intermediate', 5, 5, 5, 5, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '메모리즈 3부작 Ep3. 메모리즈', '', '{}', 'intermediate', 5, 5, 5, 5, 100, NULL, false, 0, 0),
  (uuid_generate_v4(), 'TOWER', '', '{}', 'intermediate', 4, 4, 4, 4, 180, NULL, false, 0, 0),
  (uuid_generate_v4(), '순간 이동으로 사라진 시체와 경성 데모크라시', '', '{}', 'intermediate', 1, 1, 1, 1, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '온 에어가 꺼질 때까지', '', '{}', 'intermediate', 2, 2, 2, 2, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '사랑이 맺어질 때까지', '', '{}', 'intermediate', 2, 2, 2, 2, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '결백의 헌티드 파티', '', '{}', 'intermediate', 1, 1, 1, 1, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '보성전 살인', '', '{}', 'intermediate', 4, 4, 4, 4, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '괴도 에트워스의 도전장', '', '{}', 'intermediate', 4, 4, 4, 4, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '산중호걸', '', '{}', 'intermediate', 4, 5, 4, 5, 45, 60, false, 0, 0),
  (uuid_generate_v4(), '무녀마을 금기의 저주', '', '{}', 'intermediate', 6, 6, 6, 6, 120, NULL, false, 0, 0),
  (uuid_generate_v4(), '어느 괴도의 딜레마', '', '{}', 'intermediate', 2, 2, 2, 2, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '포켓 미스터리 : 미스터리 동아리 내 연속 살인', '', '{}', 'intermediate', 3, 3, 3, 3, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '포켓 미스터리 : 저승으로의 심판', '', '{}', 'intermediate', 3, 3, 3, 3, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '포켓 미스터리 : 여신상이 염려하는 미래', '', '{}', 'intermediate', 3, 3, 3, 3, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '포켓 미스터리 : 미드나이트 매드 캠프', '', '{}', 'intermediate', 3, 3, 3, 3, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '포켓 미스터리 : 대괴도의 떡잎들', '', '{}', 'intermediate', 3, 3, 3, 3, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '작전명 너구리', '', '{}', 'intermediate', 4, 5, 4, 5, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), 'CLEAR', '', '{}', 'intermediate', 2, 2, 2, 2, 60, 70, false, 0, 0),
  (uuid_generate_v4(), 'DecalcomaNie', '', '{}', 'intermediate', 2, 2, 2, 2, 60, 70, false, 0, 0),
  (uuid_generate_v4(), 'GHOST', '', '{}', 'intermediate', 2, 2, 2, 2, 60, 70, false, 0, 0),
  (uuid_generate_v4(), '이프 : 모두가 잠든 밤에', '', '{}', 'intermediate', 2, 2, 2, 2, 120, 150, false, 0, 0),
  (uuid_generate_v4(), '미스터리 포켓 : 막이 내리다', '', '{}', 'intermediate', 1, 6, 3, 4, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '라스트 미스틱 : 주살과 인연의 경계', '', '{}', 'intermediate', 6, 6, 6, 6, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '유령섬 살인사건 : Next loop', '', '{}', 'intermediate', 4, 5, 4, 5, 90, 150, false, 0, 0),
  (uuid_generate_v4(), 'J.모리아티의 암약', '', '{}', 'intermediate', 4, 5, 4, 5, 90, 120, false, 0, 0),
  (uuid_generate_v4(), '은하의 저편에', '', '{}', 'intermediate', 5, 6, 5, 6, 60, 90, false, 0, 0),
  (uuid_generate_v4(), '우주 고릴라 팬데믹!', '', '{}', 'intermediate', 4, 5, 4, 5, 90, 150, false, 0, 0),
  (uuid_generate_v4(), '고대의 존재에게 신성모독의 제물을', '', '{}', 'intermediate', 4, 5, 4, 5, 90, 150, false, 0, 0),
  (uuid_generate_v4(), '달마저 숨은 밤', '', '{}', 'intermediate', 4, 4, 4, 4, 60, NULL, false, 0, 0),
  (uuid_generate_v4(), '여우잡이', '', '{}', 'intermediate', 4, 4, 4, 4, 90, 120, false, 0, 0),
  (uuid_generate_v4(), '변경의 마녀', '', '{}', 'intermediate', 4, 4, 4, 4, 90, NULL, false, 0, 0)
;

